using Microsoft.EntityFrameworkCore;
using TelAvivMuni_Exercise.Core.Contracts;
using TelAvivMuni_Exercise.Infrastructure;
using Xunit;

namespace TelAvivMuni_Exercise.Tests.Infrastructure;

public class AppDbContextTests : IDisposable
{
	private readonly AppDbContext _context;

	public AppDbContextTests()
	{
		var options = new DbContextOptionsBuilder<AppDbContext>()
			.UseInMemoryDatabase(databaseName: $"AppDbContextTests_{Guid.NewGuid()}")
			.Options;

		_context = new AppDbContext(options);
	}

	public void Dispose()
	{
		_context.Database.EnsureDeleted();
		_context.Dispose();
	}

	[Fact]
	public void Products_ReturnsDbSet()
	{
		// Act
		var products = _context.Products;

		// Assert
		Assert.NotNull(products);
	}

	[Fact]
	public async Task Products_CanAddAndRetrieve()
	{
		// Arrange
		var product = new Product
		{
			Id = 1,
			Name = "Test Product",
			Code = "TP001",
			Category = "Test",
			Price = 99.99m,
			Stock = 10
		};

		// Act
		_context.Products.Add(product);
		await _context.SaveChangesAsync();
		var retrieved = await _context.Products.FindAsync(1);

		// Assert
		Assert.NotNull(retrieved);
		Assert.Equal("Test Product", retrieved.Name);
		Assert.Equal("TP001", retrieved.Code);
		Assert.Equal("Test", retrieved.Category);
		Assert.Equal(99.99m, retrieved.Price);
		Assert.Equal(10, retrieved.Stock);
	}

	[Fact]
	public async Task Products_CanUpdate()
	{
		// Arrange
		var product = new Product { Id = 1, Name = "Original", Code = "O001", Category = "Cat", Price = 10.00m, Stock = 5 };
		_context.Products.Add(product);
		await _context.SaveChangesAsync();

		// Act
		product.Name = "Updated";
		product.Price = 20.00m;
		await _context.SaveChangesAsync();

		// Assert
		var retrieved = await _context.Products.FindAsync(1);
		Assert.NotNull(retrieved);
		Assert.Equal("Updated", retrieved.Name);
		Assert.Equal(20.00m, retrieved.Price);
	}

	[Fact]
	public async Task Products_CanDelete()
	{
		// Arrange
		var product = new Product { Id = 1, Name = "ToDelete", Code = "D001", Category = "Cat", Price = 10.00m, Stock = 5 };
		_context.Products.Add(product);
		await _context.SaveChangesAsync();

		// Act
		_context.Products.Remove(product);
		await _context.SaveChangesAsync();

		// Assert
		var retrieved = await _context.Products.FindAsync(1);
		Assert.Null(retrieved);
	}

	[Fact]
	public async Task Products_IdIsNotAutoGenerated()
	{
		// Arrange - Product with explicit Id
		var product = new Product { Id = 42, Name = "Explicit Id", Code = "E001", Category = "Cat", Price = 10.00m, Stock = 5 };

		// Act
		_context.Products.Add(product);
		await _context.SaveChangesAsync();

		// Assert - Id should remain as explicitly set
		var retrieved = await _context.Products.FindAsync(42);
		Assert.NotNull(retrieved);
		Assert.Equal(42, retrieved.Id);
	}

	[Fact]
	public async Task Products_CanQueryByProperties()
	{
		// Arrange
		_context.Products.AddRange(
			new Product { Id = 1, Name = "Laptop", Code = "LAP001", Category = "Electronics", Price = 999.99m, Stock = 10 },
			new Product { Id = 2, Name = "Mouse", Code = "MOU001", Category = "Electronics", Price = 29.99m, Stock = 50 },
			new Product { Id = 3, Name = "Desk", Code = "DSK001", Category = "Furniture", Price = 199.99m, Stock = 5 }
		);
		await _context.SaveChangesAsync();

		// Act
		var electronics = await _context.Products
			.Where(p => p.Category == "Electronics")
			.ToListAsync();

		// Assert
		Assert.Equal(2, electronics.Count);
		Assert.All(electronics, p => Assert.Equal("Electronics", p.Category));
	}

	[Fact]
	public async Task Products_HandlesNullableProperties()
	{
		// Arrange
		var product = new Product
		{
			Id = 1,
			Name = null,
			Code = null,
			Category = null,
			Price = 0m,
			Stock = 0
		};

		// Act
		_context.Products.Add(product);
		await _context.SaveChangesAsync();

		// Assert
		var retrieved = await _context.Products.FindAsync(1);
		Assert.NotNull(retrieved);
		Assert.Null(retrieved.Name);
		Assert.Null(retrieved.Code);
		Assert.Null(retrieved.Category);
	}

	[Fact]
	public async Task Products_PreservesDecimalPrecision()
	{
		// Arrange
		var product = new Product
		{
			Id = 1,
			Name = "Precision Test",
			Code = "PT001",
			Category = "Test",
			Price = 12345.67m,
			Stock = 1
		};

		// Act
		_context.Products.Add(product);
		await _context.SaveChangesAsync();

		// Assert
		var retrieved = await _context.Products.FindAsync(1);
		Assert.NotNull(retrieved);
		Assert.Equal(12345.67m, retrieved.Price);
	}
}
